### ISSUE TITLE
Chrome and Firefox are triggered concurrently on 'iPhone' and 'Samsung' devices

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe-browser-provider-browserstack#100]
I have a plan to run 5 parallel tests on BrowserStack, and I've set up nightly regression tests to run through each BrowserStack browser sequentially. This has been fine when I specify the browser specifically; `browserstack:chrome@80.0:Windows 10` or `browserstack:firefox@......`.

However when specifying a _DEVICE_ to run our tests on (`browserstack:Samsung Galaxy S10 Plus` or `browserstack:iPhone X`), _BOTH_ Chrome and Firefox are triggered concurrently for these tests, which exceeds my limit and causes the tests to fail/crash.

Is there a way we can limit this to run a specific browser on the device of our choice? I would love to run native Safari on iPhones, as well as Chrome (just not concurrently due to my plan limitations).

**Comment by AlexKamaev** [comment]
Could you please provide more details on how you are running your tests? I would appreciate it if you create a sample project and testcafe command so that I can reproduce the issue.

I tried to run the `testcafe "browserstack:Samsung Galaxy S10 Plus" tests/ -c 5` command with the following set of tests:

```JS
fixture `fixture`
    .page `http://example.com`;

test(`test1`, async t => {
    await t.click('h1');
});

test(`test2`, async t => {
    await t.click('h1');
});

test(`test3`, async t => {
    await t.click('h1');
});

test(`test4`, async t => {
    await t.click('h1');
});

test(`test5`, async t => {
    await t.click('h1');
});
```
All tests were run concurrently and in the same `androidbrowser`.

**Comment by rob4629** [comment]
Hey, I think this issue can be closed. I was running the command through an NPM script on our CI server... and it looks like the `$BROWSER` arg wasn't being passed properly.

Sorry for any inconvenience caused.
