### ISSUE TITLE
When the master will be released?

### ISSUE THREAD

**Issue by yashLadha** [DevExpress/testcafe-browser-provider-browserstack#101]

**Comment by yashLadha** [comment]
@AndreyBelym

**Comment by yashLadha** [comment]
@VasilyStrelyaev

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. `testcafe-browser-provider-browserstack@1.12.0` will be released after the `testcafe@1.8.2` release. I will post a message in this thread when it is available.

**Comment by yashLadha** [comment]
Thanks for the update @AndreyBelym

**Comment by AndreyBelym** [comment]
Thank you for your patience, `testcafe-browser-provider-browserstack@1.12.0` is available now.

**Comment by yashLadha** [comment]
Awesome 🎉

**Comment by yashLadha** [comment]
Hey,

I can see that the `testcafe` has released a new version, but it is still pointing to the alpha version of `browserstack-provider`. 

https://github.com/DevExpress/testcafe/blob/master/package.json#L200

When can we expect the release of the [master](https://github.com/DevExpress/testcafe-browser-provider-browserstack) and also the update in the [testcafe-core](https://github.com/DevExpress/testcafe) library as well.

**Comment by Farfurix** [comment]
@yashLadha 

The `testcafe-browser-provider-browserstack@1.13.0` has been released.

> I can see that the testcafe has released a new version, but it is still pointing to the alpha version of browserstack-provider.
> https://github.com/DevExpress/testcafe/blob/master/package.json#L200

This is our **development** dependency, its version may differ from the latest provider version.
