### ISSUE TITLE
[docs] Document the BROWSERSTACK_CAPABILITIES_CONFIG_PATH 

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-provider-browserstack#109]
https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/102/files implements a way to store additional capabilities in JS or JSON file and loading them via specifying the path to the config file via the BROWSERSTACK_CAPABILITIES_CONFIG_PATH environment variable.

**Comment by rafaellages-hotmart** [comment]
Ive made a pr that covers it #111

**Comment by Farfurix** [comment]
@rafaellages-hotmart 

Hello,

Thank you, we'll check [your PR](https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/111).

**Comment by AndreyBelym** [comment]
Closed by DevExpress/testcafe-browser-provider-browserstack#115.
