### ISSUE TITLE
Intermittently unable to "establish one or more browser connections"

### ISSUE THREAD

**Issue by ksoldau** [DevExpress/testcafe-browser-provider-browserstack#110]
**The problem:** 
_Sometimes_ when I run my tests on BrowserStack from the command line (or from CI), they fail with the error: `ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.` 

This has happened to me for almost a day straight a week ago while trying to run `'browserstack:iPhone 7'` and a few times with `'browserstack:iPhone 8'` I don't think it's ever happened to me with `'browserstack:Samsung Galaxy S6'`, but I'm not positive about that.

**Steps I'm taking when this happens:**
1. I try and run tests on browserstack via my local command line (or CI). 
    a. Here's the command: `BROWSERSTACK_USERNAME=************ BROWSERSTACK_ACCESS_KEY=*********** BROWSERSTACK_USE_AUTOMATE=1 BROWSERSTACK_CONSOLE=verbose BROWSERSTACK_NETWORK_LOGS=true testcafe 'browserstack:iPhone 7'`
2. Then it says `ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.` (See picture below).
3. When this happens, the BrowserStack UI indicates that something is queuing,but it never moves to running.

This is what the entirety of the console message is when it fails: 
![image (2)](https://user-images.githubusercontent.com/3526718/77404982-a37da100-6e06-11ea-948e-5c423413c37a.png)

**Anyone know what causes this flake?**
I've been in touch with BrowserStack, but haven't had much luck figuring out yet and am not sure if the problem lies with them or somewhere else, so figured I should try posting in here as well.

Thanks for any help!

**Comment by Farfurix** [comment]
@ksoldau 

Hello,

I wasn't able to reproduce it. Here is my configuration:

**package.json**:
```json
{
  "name": "i110-browserstack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "testcafe": "^1.8.3",
    "testcafe-browser-provider-browserstack": "^1.13.0-alpha.1"
  }
}
```

**.testcaferc.json**:
```json
{
  "browsers": "browserstack:iPhone 7@10.3",
  "src": "./tests/test.js",
  "skipJsErrors": true
}
```

**tests/test.js**:
```js
fixture `Fixture`
    .page `https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/110`;

test('test 1', async t => {
    await t.expect(true).ok();
});

test('test 2', async t => {
    await t.expect(true).ok();
});

test('test 3', async t => {
    await t.expect(true).ok();
});

test('test 4', async t => {
    await t.expect(true).ok();
});

test('test 5', async t => {
    await t.expect(true).ok();
});

test('test 6', async t => {
    await t.expect(true).ok();
});

test('test 7', async t => {
    await t.expect(true).ok();
});

test('test 8', async t => {
    await t.expect(true).ok();
});

test('test 9', async t => {
    await t.expect(true).ok();
});

test('test 10', async t => {
    await t.expect(true).ok();
});

test('test 11', async t => {
    await t.expect(true).ok();
});

test('test 12', async t => {
    await t.expect(true).ok();
});

test('test 13', async t => {
    await t.expect(true).ok();
});

test('test 14', async t => {
    await t.expect(true).ok();
});

test('test 15', async t => {
    await t.expect(true).ok();
});

```

Result:
![Capture-1](https://user-images.githubusercontent.com/30019338/77540901-f57d0000-6eb4-11ea-83e9-7385ff5a9de6.PNG)

Could you please send us a minimal project? We will examine it and check for a suitable solution.

**Comment by ksoldau** [comment]
Yup! Might be a few days before I can send something through, but I will.

**Comment by christopherrolfe198** [comment]
Hi we are also experiencing this issue - I don't think it's related to test code.

Our situation is that we run our e2e tests nightly over browserstack and these intermittently fail due to this error and our code has not changed, E.G. over the weekend.

I think it's more likely to be on browserstacks end or between where the tests are executed and browserstack - a bad network etc like the message indicates. What brought me here was looking for a way to auto retry when receiving these kind of messages.

**Comment by Dmitry-Ostashev** [comment]
@christopherrolfe198 Currently, TestCafe is able to restart the browser that isn't responding.

Could you please give us a more detailed description of your case? What TestCafe version do you use?

**Comment by christopherrolfe198** [comment]
Hi @Dmitry-Ostashev 

We are using testcafe ^1.3.2 and testcafe-browser-provider-browserstack ^1.9.0.

Unfortunately, we don't seem to keep our logs for longer than about a week so I can't really provide any more detail than this at this stage. Only that we get the same message as mentioned above.

I'll keep an eye out so that when this happens again I can provide you with as many details as possible.

**Comment by miherlosev** [comment]
@christopherrolfe198 

Thank for cooperation. 
Also, I suggest you to use the latest module versions: `testcafe@1.8.3` and `testcafe-browser-provider-browserstack@1.12.0`. We completely work on bug fixes and stability improvements. Updating to the latest module versions can fix the problems described above.

**Comment by ksoldau** [comment]
Browserstack has gotten back to me and said that it's an issue they've resolved on their end. Closing the issue as it's not this package's problem, and seems to have been resolved by Browserstack.
