### ISSUE TITLE
`request-promise` is deprecated

### ISSUE THREAD

**Issue by yashLadha** [DevExpress/testcafe-browser-provider-browserstack#112]
`request-promise` library is deprecated and thus we should port the base code to some other alternative. 

There is an open issue on the repo for a list of alternatives https://github.com/request/request/issues/3143. 

According to me, we don't have very much dependency on these network requests and thus moving with [node-fetch](https://www.npmjs.com/package/node-fetch) might be a good solution.

**Comment by miherlosev** [comment]
Hi @yashLadha 

Thank you for pointing out this issue. We will consider replacing the `request-promise` module here and in other module connected with TestCafe.
