### ISSUE TITLE
Edge version 81 is reported as Chrome 81

### ISSUE THREAD

**Issue by wjcheng1** [DevExpress/testcafe-browser-provider-browserstack#116]
When I run the following command: `testcafe 'browserstack:edge@81.0:Windows 10' e2e/testcafe/ --skip-js-errors --test-meta level=sanity` 

The version reported back form testcafe is Chrome 81 and not Edge 81:

`The "filter" option from the configuration file will be ignored.`
 
 `Running tests in:`
 
 `- Chrome 81.0.4044 / Windows 10.0.0`

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue.
I see the following output:
```
D:\projects\test>testcafe 'browserstack:edge@81.0:Windows 10' test.js
 Running tests in:
 - Microsoft Edge 81.0.416.53 / Windows 10 (https://automate.browserstack.com/builds/94cf7db2319c65......../sessions/a1df289ba999d62a........)

 My Fixture
 √ My test

```
Could you please run the `testcafe -b browserstack` command and check that the 'browserstack:edge@81.0:Windows 10' browser is in the list.
Could you also check the video Browserstack recorded? Does Browserstack run the test in Chrome or in Edge?

I look forward to your answers.

**Comment by wjcheng1** [comment]
It does run the tests in Edge but just reports it as Chrome.  And Edge 81 is listed:

`(base) MacBook-Pro-3:frontend wcheng$ $(npm bin)/testcafe -b browserstack | grep edge@81 -i
"browserstack:edge@81.0:OS X Catalina"
"browserstack:edge@81.0:OS X Mojave"
"browserstack:edge@81.0:OS X High Sierra"
"browserstack:edge@81.0:OS X Sierra"
"browserstack:edge@81.0:Windows 10"
"browserstack:edge@81.0:Windows 8.1"
"browserstack:edge@81.0:Windows 8"
"browserstack:edge@81.0:Windows 7"
`

**Comment by AlexanderMoiseev** [comment]
Hello, 
We have reproduced the issue with Testcafe v.1.2.1. In the latest version however it works as expected. Please update to testcafe v.1.8.4 and let us know if this helps.

**Comment by wjcheng1** [comment]
Ok, I was using 1.5 and updating to 1.8.4 seems to have fixed it.  thanks

**Comment by AlexSkorkin** [comment]
Thank you for the update. I'm happy to hear that the issue is resolved.
