### ISSUE TITLE
Screenshots not full screen

### ISSUE THREAD

**Issue by mineshhalai** [DevExpress/testcafe-browser-provider-browserstack#118]
When doing screenshots I only get part of the screen. Would we be able to get the full page screenshots?

**Comment by Dmitry-Ostashev** [comment]
Try switching to the Browserstack Automate API by setting the `BROWSERSTACK_USE_AUTOMATE` environment variable to 1. This will make TestCafe detect the page area. Take a look at the following thread for details: https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/51.
