### ISSUE TITLE
change the resolution

### ISSUE THREAD

**Issue by Blurri** [DevExpress/testcafe-browser-provider-browserstack#12]
Hi,
I'm not sure if this is the right place to ask this question. 
Is there a way to change the resolution of the browser with this plugin?
We try to run our e2e tests with your plugin against browserstack and 
the only problem is at the moment that the screen is too small.

**Comment by AndreyBelym** [comment]
Hello @Blurri! Unfortunately it's not possible yet, but will it help you if we add a `BROWSERSTACK_RESOLUTION` environment variable to specify the desired resolution?

**Comment by Blurri** [comment]
Yes that would help us a lot.
Thank you.

**Comment by hoploop** [comment]
News about this ?

**Comment by FDiskas** [comment]
I want it to :)

**Comment by hoploop** [comment]
I created my workaround:
- Checkout the src
- Added the lib on my local repo
- Changed src/index.js line 250:
 async openBrowser (id, pageUrl, browserName) {
        var capabilities = this._generateCapabilities(browserName);
        var connector    = await this._getConnector();

        capabilities.resolution           = '1280x800';
        capabilities.timeout              = TESTS_TIMEOUT;
      
- Gulp build
- Imported my local library
- For now is hard coded, I will modify to take input process.env args

**Comment by FDiskas** [comment]
But it needs to be some kind of validation https://www.browserstack.com/automate/capabilities
Resolution dependents on OS and version. :smiley:

**Comment by hoploop** [comment]
https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/35
https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/34

**Comment by AndreyBelym** [comment]
Closed by #44.
