### ISSUE TITLE
browserstack command to change orientation to landscape mode in iOS and andriod devices

### ISSUE THREAD

**Issue by vasantverma-LM** [DevExpress/testcafe-browser-provider-browserstack#123]
I need to run my testcafe tests in landscape mode in some iOS and android devices.
I have used the below browser alias for these devices:
**//For iOS v10 and iOS v13**
['browserstack:iPhone 7','browserstack:iPhone 11']
**//For andriod v9.0 and v10.0**
 ['browserstack:Google Pixel 3 XL','browserstack:Google Pixel 4 XL'] .

By default the orientation is in portrait mode. What command or additional parameters I need to pass to run my testcafe tests in landscape mode?

**Comment by wentwrong** [comment]
The BrowserStack provider for TestCafe can use the BrowserStack [JS Test API](https://github.com/browserstack/api) and [Automate API](https://www.browserstack.com/automate/node).

The JS test API is a BrowserStack-specific REST API, and its documentation doesn't mention that different screen orientations are supported by the API.
The Automate API is a WebDriver-based API. Theoretically, it should support the [setOrientation](http://v4.webdriver.io/api/mobile/orientation.html) method, but some StackOverflow answers indicate that this method is not supported by the BrowserStack API implementation.

This means that we are not sure if it is possible to change the screen orientation for BrowserStack mobile devices. We we will need some time to research this.

**Comment by vasantverma-LM** [comment]
@wentwrong Do we have any update on this

**Comment by AlexSkorkin** [comment]
Once we get any results, we will share them here.
