### ISSUE TITLE
How to send cdpPort information to Browserstack

### ISSUE THREAD

**Issue by abhinaba-ghosh** [DevExpress/testcafe-browser-provider-browserstack#124]
Hi, 

[testcafe-lighthouse](https://github.com/abhinaba-ghosh/testcafe-lighthouse) library needs remote debugging port information to execute audits. Is there a way to send that information. I am trying out things, but not working, unfortunately. 

Getting output like below:
```ssh
Type "testcafe -h" for help.
Abhinabas-MacBook-Air:testcafe-lighthouse abhinabaghosh$ npx testcafe "browserstack:Chrome@81.0:Windows 10:cdpPort=9222" "test/audit.spec.js"
ERROR Unable to find the browser. "browserstack:Chrome@81.0:Windows 10:cdpPort=9222" is not a browser alias or path to an executable file.
```

any guidance will be helpful.

**Comment by ayemelyanenko-chegg** [comment]
+1, I am also interested to see if this is possible.

**Comment by wentwrong** [comment]
BrowserStack doesn't provide an API to work with the DevTools protocol. Therefore, at this moment there is no way to achieve this functionality.
