### ISSUE TITLE
Safari browsers not working

### ISSUE THREAD

**Issue by Esteban26** [DevExpress/testcafe-browser-provider-browserstack#125]
I'm facing an error while trying to run some test cases on BS through test cafe. I run a local server when everything works properly then I run it indicating test cases must be executed with Safari 6.2, Safari 7.1 and Safari 8

The command like I'm using looks like this.

 BROWSERSTACK_USERNAME=myusername BROWSERSTACK_ACCESS_KEY=myaccesskey testcafe "-S" "-s" "artifacts/screenshots" "-p" "${USERAGENT}\${FIXTURE}_${TEST}.png" "browserstack:safari@6.2:OS X Mountain Lion, browserstack:safari@7.1:OS X Mavericks" "test/cases/path/*.spec.ts" "--app" "node test/serve.js" "--hostname" "localhost" "--speed" "1"

 When I'm trying to run it, the JS code I have inside my test cases is not executed, I checked it and when I open the interactive session I see a lot of errors from testcafe_core and hammerhead libraries.

Any idea why this is happening? Are Safari 6, 7, and 8 supported?

The test cafe version I'm using is: 1.8.5

**Comment by Farfurix** [comment]
Related to [https://github.com/DevExpress/testcafe/issues/5228](https://github.com/DevExpress/testcafe/issues/5228).

@Esteban26

Hello,

Our browser/platform support is related to officially supported platforms. The OS X Mountain Lion and OS X Mavericks are not currently supported.

> Any idea why this is happening? Are Safari 6, 7, and 8 supported?

Since these versions are related to the operating systems that aren't officially supported (OS X 10.8 Mountain Lion, OS X Mavericks and OS X Yosemite), we cannot guarantee that your tests will work correctly in Safari 6, 7, and 8.

If you face any issues in the latest Safari browser, please feel free to open a new issue.

**Comment by Esteban26** [comment]
Thanks for your quick response @Farfurix , I have just one more question, is there any document or something like that where you show the supported browser versions?

**Comment by Farfurix** [comment]
@Esteban26 

We have a help section related to browser support: [Officially Supported Browsers](https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#officially-supported-browsers).

**Comment by Esteban26** [comment]
Thank you @Farfurix

**Comment by Esteban26** [comment]
Hi @Farfurix I've just one more question about this, is there any official source provided by apple were we can check the supported versions of their browsers?

**Comment by Farfurix** [comment]
Hello,

To determine the minimal supported OS and browser version, you can use these steps:
1. Find the oldest supported OS - [macOS 10.13 High Sierra](https://en.wikipedia.org/wiki/MacOS_High_Sierra) has the "Extended support ends in November 2020" support status.
2. We can see [here](https://en.wikipedia.org/wiki/Safari_(web_browser)) that Safari 11 was released as a part of macOS High Sierra. It is highly recommended to use the latest available Safari browser for each supported OS. It means you need to install the latest updates (or choose the latest browser in a CI configuration) on your supported OS.

This way, you can determine the OS and browser version you are looking for.

**Comment by Esteban26** [comment]
Got it, thank you @Farfurix

**Comment by Farfurix** [comment]
@Esteban26 

You are welcome.
