### ISSUE TITLE
Add browser to mobile browser aliases

### ISSUE THREAD

**Issue by benquinteros** [DevExpress/testcafe-browser-provider-browserstack#126]
Would be great if we could add the browser e.g

`browserstack:chrome@84.0:iPhone 11@13`

So different browsers can be tested on mobile.

**Comment by miherlosev** [comment]
Hi @benquinteros 
 
The `testcafe-browser-provider-browserstack` module uses a BrowserStack API and requests the list of browsers .
The BrowserStack doesn't allow you to specify such a condition for a browser - Chrome 84 on IPhone 11 with iOS 13.  
So, we cannot specify this device either.
I suggest you contact the BrowserStack team and discuss the possibility of adding this functionality.
