### ISSUE TITLE
BROWSERSTACK_TIMEZONE seems to have no effect on time zone

### ISSUE THREAD

**Issue by harry7771** [DevExpress/testcafe-browser-provider-browserstack#127]
I've tried passing in a few different environment variables:
BROWSERSTACK_TIMEZONE: "UTC"
BROWSERSTACK_TIMEZONE: "Chicago"
BROWSERSTACK_TIMEZONE: "New_York"

With all of these, '0' is returned for the following:  var timezone = new Date().getTimezoneOffset();

Thanks for whatever help you can give.

**Comment by miherlosev** [comment]
Hi @harry7771 

I've checked the tests and code and this feature should work as expected. Could you please create a complete example that I can reproduce locally?

**Comment by harry7771** [comment]
I'll work on that and try to submit something back before the end of the week.  In the meantime, if you happen to have any thoughts on what I might be doing wrong on my end, feel free to post that.  As it is, I'm just passing in the variable BROWSERSTACK_TIMEZONE with values like Chicago or New_York.  Thanks.

**Comment by harry7771** [comment]
Adding clarification to original post.  Original:
    "With all of these, '0' is returned for the following: var timezone = new Date().getTimezoneOffset();"

More specifically, the value returned for Date().getTimezoneOffset follows the local machine timezone.  That may be 0 on one machine and 300 on another.  Either way, the value is unaffected by whatever value is set for BROWSERSTACK_TIMEZONE.

**Comment by harry7771** [comment]
@miherlosev  I have a GitHub repo available for reproducing.  Is there a way I can send that to you privately?

**Comment by miherlosev** [comment]
Yes, of course, you can send it at support@devexpress.com.

**Comment by harry7771** [comment]
thank you,  I've emailed the project URL.

**Comment by AndreyBelym** [comment]
Thank you for sharing your project. The `BROWSERSTACK_TIMEZONE` environment variable should be set before browsers are launched. It means it cannot be set through `process.env` in tests. You can use OS-specific options like `export BROWSERSTACK_TIMEZONE=XXX` (macOS, Linux) and `set BROWSERSTACK_TIMEZONE=XXX` (Windows) or use the [cross-env](https://www.npmjs.com/package/cross-env) module to set it before starting TestCafe.

Please also note, that this feature is only available for Android browsers, according to the [BrowserStack](https://www.browserstack.com/app-automate/device-features#timezone) docs. I didn't find a command or a configuration file that specifies the browser in your project, so I feel that I should warn you about this limitation.
