### ISSUE TITLE
How to select the browser on mobile devices?

### ISSUE THREAD

**Issue by Esteban26** [DevExpress/testcafe-browser-provider-browserstack#128]
I'm using browserstack and testcafe together to create a mobile suite of test cases.

When I run this command:

testcafe -b browserstack

I'm getting the list of available browsers/environments, for example: **browserstack:Samsung Galaxy A10@9.0**

But for that certain device and android version I'd like to test google chrome and firefox, so what is the text I should set to execute the test case there. I noticed that tests run on chrome by default.

**Comment by LavrovArtem** [comment]
Hello,
This issue is a duplicate of #126.

**Comment by Esteban26** [comment]
Thank you @LavrovArtem
