### ISSUE TITLE
Is there way to run Headless mode against browserstack's chrome and firefox browsers 

### ISSUE THREAD

**Issue by shyedhu** [DevExpress/testcafe-browser-provider-browserstack#129]
As we know current testcafe support headless mode for chrome and firefox browsers on locally and docker like below example , 
Is there way to run same Headless mode against browserstack's chrome and firefox browsers via testcafe ? if so please let me know ? Thanks !

Here's example on locally
testcafe "chrome:headless"  tests/test.js

testcafe "firefox:headless"  tests/test.js

**Comment by Farfurix** [comment]
@shyedhu 

Hello,

We answered a similar question [here](https://testcafe-discuss.devexpress.com/t/browserstack-mobile-how-to-run-tests-in-parallel-on-ios-and-android/770/1):
> The 'Headless' term means that the browser doesn't require a graphical user interface. From this point of view, all browsers on Browserstack are headless - because they don't produce graphical interface on a machine that runs TestCafe. So, you can use TestCafe with the BrowserStack provider on terminal-only Linux servers. But on the Browserstack side, browsers are launched in their regular, non-headless configuration, and unfortunately, there is no way to force them to start in the headless mode.
