### ISSUE TITLE
Problems running tests on mobile devices

### ISSUE THREAD

**Issue by vmattos** [DevExpress/testcafe-browser-provider-browserstack#13]
Hello! I'm having problems running the tests on mobile devices with the programming interface
It triggers the test job on Browserstack, but it says that it could not connect to the server :( 

The same tests on the same devices pass when I use the command line interface
The tests pass on desktop browsers on both the command line and programming interfaces
Is there any known issue about this?

ps: The devices I'm using are: `iPhone 6S@9.3` and `Samsung Galaxy S5`

**Comment by AndreyBelym** [comment]
Hello @vmattos! Can you share the code that uses TestCafe API? Are you using VPN or proxy?

We also experienced some issues with Android simulator last week: despite jobs were created successfully, simulators were unable to start or open test URL. It looked like a problem on Browserstack side. But we didn't have any problem with iOS simulators.

**Comment by AndreyBelym** [comment]
Closing it without response
