### ISSUE TITLE
t.pressKey does not seem to work in browserstack:ie@11

### ISSUE THREAD

**Issue by oshi97** [DevExpress/testcafe-browser-provider-browserstack#141]
We're trying to use t.pressKey('down') for a very simple test
```js
  const searchComponent = FacetsPage.getSearchComponent();
  await searchComponent.submitQuery();

  const firstOption = Selector('.yxt-SortOptions-optionSelector').nth(0);
  const secondOption = Selector('.yxt-SortOptions-optionSelector').nth(1);

  await t.click(await firstOption);
  await t.pressKey('down');

  const isSecondOptionFocused = await secondOption().focused;

  await t.expect(isSecondOptionFocused).ok();
```
we noticed that our tests on browserstack ie11 always hang  on the t.pressKey('down') line. Is this a known issue?

**Comment by AlexKamaev** [comment]
Hello. This is not a known issue, and it's difficult to determine its cause without a reproducible example. Could you please share your website's public URL or create a sample that we can run on our machine? Could you please also specify if you see the issue in your local IE11 without BrowserStack?

In addition, I noticed a typo in the following line:

```JS
await t.click(await firstOption);
```

The `await` statement before `firstOption` is redundant.
