### ISSUE TITLE
Error on screenshot with automate and js execution

### ISSUE THREAD

**Issue by eisenreich** [DevExpress/testcafe-browser-provider-browserstack#146]
Versions:
```
"testcafe": "^1.10.0",
"testcafe-browser-provider-browserstack": "^1.13.1",
```

Running on:

```
Operating System: Ubuntu 18.04.4 LTS
Kernel: Linux 5.3.0-40-generic
Architecture: x86-64
```

When running a test that fails and a screenshot should be taken, the following errors happen:

* **with `BROWSERSTACK_USE_AUTOMATE=0` (JS-API)**
  Here the screenshots are local and in the cloud available.

  ```
  Warnings (2):
   --
    Was unable to take a screenshot due to an error.
  
    Error: Unable to locate the page area in the browser window screenshot at /opt/ui-tests/tmp/screenshots/2020-12-18_11-15-41/test-1/Chrome_88.0.4324.27_macOS_11.0.1/errors/1.png,
    because the page area mark with ID 3701261365 is not found in the screenshot.
        at calculateClipInfo (/opt/ui-tests/node_modules/testcafe/src/screenshots/crop.js:119:19)
        at Object.cropScreenshot (/opt/ui-tests/node_modules/testcafe/src/screenshots/crop.js:136:18)
        at async_queue_1.addToQueue (/opt/ui-tests/node_modules/testcafe/src/screenshots/capturer.js:146:40)
        at process._tickCallback (internal/process/next_tick.js:68:7)
   --
    Was unable to take a screenshot due to an error.
  
    Error: Unable to locate the page area in the browser window screenshot at /opt/ui-tests/tmp/screenshots/2020-12-18_11-15-41/test-1/Chrome_88.0.4324.27_macOS_11.0.1/errors/2.png,
    because the page area mark with ID 2866116671 is not found in the screenshot.
        at calculateClipInfo (/opt/ui-tests/node_modules/testcafe/src/screenshots/crop.js:119:19)
        at Object.cropScreenshot (/opt/ui-tests/node_modules/testcafe/src/screenshots/crop.js:136:18)
        at async_queue_1.addToQueue (/opt/ui-tests/node_modules/testcafe/src/screenshots/capturer.js:146:40)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  
  ```

* **with `BROWSERSTACK_USE_AUTOMATE=1` (AUTOMATE-API)**

  Here the screenshots are **NOT** local and in the cloud available.

  The image is missing:
  ![image](https://user-images.githubusercontent.com/12513137/102610921-4eb94d80-412e-11eb-8313-e029c3674e67.png)

  ```
  1/1 failed (59s)
  
   Warnings (1):
   --
    Was unable to take a screenshot due to an error.
  
    Error: API error 13:
  
    An unknown server-side error occurred while processing the command.
        at request_api_1.default.then.response (/opt/ui-tests/node_modules/testcafe-browser-provider-browserstack/src/backends/automate.js:69:23)
        at invokeCallback (/opt/ui-tests/node_modules/pinkie/index.js:60:12)
        at Array.forEach (<anonymous>)
        at publish (/opt/ui-tests/node_modules/pinkie/index.js:147:32)
        at Array.publishFulfillment (/opt/ui-tests/node_modules/pinkie/index.js:152:2)
        at Immediate.asyncFlush (/opt/ui-tests/node_modules/pinkie/index.js:17:19)
        at runCallback (timers.js:706:11)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        at process.topLevelDomainCallback (domain.js:126:23)
  ```

**Comment by AlexKamaev** [comment]
We have had a similar issue: [https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/51](https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/51).

However, it was related only to the JS API, so we recommended to switch to the Automate API: [https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/51#issuecomment-460156835](https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/51#issuecomment-460156835). As I see, the Automate API causes an error in your case. This issue is unclear to us. Could you please share your project and test code to demonstrate the issue? If you cannot share your project here, you can send it at support@devexpress.com.

**Comment by eisenreich** [comment]
A happy new year! 🎉

Today I did more investigation and when I execute the same on windows it's working. So it seems to be an issue on a linux system. I try to setup up a test project for reproduction.

**Comment by eisenreich** [comment]
When I execute a plain testcafe test on linux it's working.

Only when I use the npm package `gherkin-testcafe` on linux this error happens - do you have any idea how to investigate further?

**Comment by eisenreich** [comment]
I created a simplified example project, to narrow down the issue with the following three test cases:
- Open google.com and search for a word - with `gherkin-testcafe` - **success**
- Open google.com and select a invalid button -  with `gherkin-testcafe` - **failed with the error above**
- Open a website from the local tunnel and select a invalid button - with `gherkin-testcafe` - **failed with the error above**
- Open google.com and search for a word - without `gherkin-testcafe` - **success**
- Open google.com and select a invalid button -  without `gherkin-testcafe` - **failed with the error above**
- Open a website from the local tunnel and select a invalid button - without `gherkin-testcafe` - **failed with the error above**

So it's not related with the `gherkin-testcafe` project, but with the local tunnel.

I uploaded the project to: 

You can execute the plain tests with `npm run debug:plain`. Before you should adjust the IP-Address in the `plain/tests.ts` file to a running web service on your local computer.

**Comment by miherlosev** [comment]
Hi @eisenreich, 

The `gherkin-testcafe` is a third party module. So, please, ask this question in the [gherkin-testcafe](https://github.com/Arthy000/gherkin-testcafe) repository.

**Comment by eisenreich** [comment]
Hi @miherlosev,

you should read until the end - it's not issued by the `gherkin-testcafe` module, but with the local tunnel. Please read last post above.

**Comment by wentwrong** [comment]
Hello, @eisenreich

I'm not able to reproduce this issue with the example from the repo you created.

I adjusted the IP address in the test files to be in accordance with my local tunnel page address (which I've created via [localtunnel](https://www.npmjs.com/package/localtunnel) package). Screenshots were taken without any warnings and displayed in the BrowserStack dashboard.

Could you please clarify in which exact environment the error can be reproduced? Because it seems that on Windows both `npm run debug:plain` and `npm run debug:gherkin` commands from your example work fine.

**Comment by eisenreich** [comment]
Hello @wentwrong,

first thank you for you investigation.

I found the issue. It was issued due to a wrong version of the `~/.browserstack/BrowserStackLocal`. After I deleted this directory it worked.

So it seems like that when the package `browserstack-local` is updated via npm, only the version will be updated, but the old binary is not replaced by the old one.

**Comment by wentwrong** [comment]
It's great to hear that you found the cause of the problem. There is an issue in the repo of the "browserstack-local" package: [Pin the browserstack-local binary to the release](https://github.com/browserstack/browserstack-local-nodejs/issues/115). So, until it is implemented, there seems to be no other way to update the binary than to do it manually. Thanks for pointing this out.
