### ISSUE TITLE
Support `--test-scheduling` option

### ISSUE THREAD

**Issue by stucox** [DevExpress/testcafe-browser-provider-browserstack#150]
[These BrowserStack docs](https://www.browserstack.com/docs/automate/selenium/getting-started/nodejs/testcafe#use-test-scheduling-functionality-in-tests) describe how to use Test Scheduling (i.e. run each test in a separate BrowserStack session) with TestCafe, via a `--test-scheduling` option

However it requires using BrowserStack's forks of both `testcafe` and `testcafe-browser-provider-browserstack`, which are somewhat behind the DevExpress forks of both of those libraries:

* https://www.npmjs.com/package/@browserstack/testcafe
* https://www.npmjs.com/package/@browserstack/testcafe-browser-provider-browserstack

Are there any plans to incorporate BrowserStack's changes into `testcafe` and `testcafe-browser-provider-browserstack` such that Test Scheduling can be used?

**Comment by AlexKamaev** [comment]
Hi
We have some plans to integrate BrowserStack changes but I cannot give you an estimate. Frankly, I am not sure we will implement the `--test-scheduling` option.
