### ISSUE TITLE
Session not running on https server for android

### ISSUE THREAD

**Issue by SaranshBS** [DevExpress/testcafe-browser-provider-browserstack#162]
Not able to run a HTTPS on android devices on Browserstack. Tried to narrow down, saw a hardcoded code [here](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/466ded007f965e4478ca3c954c7360a87c299806/src/index.js#L241)

**Comment by felis2803** [comment]
Hello @SaranshBS,

I tested TestCafe on several different Android devices in BrowserStack and found no issues. Please send me your test, config, run command, and error messages.

**Comment by chiragshah-bs** [comment]
@felis2803 Please find the details below - 

### Test
```
import { Selector } from 'testcafe';

fixture('TestCafe example page').page(
  'https://devexpress.github.io/testcafe/example/'
);

test("Should submit developer's name successfully", async user => {
  // To interact with a DOM element, we must use the Selector function
  const interfaceSelect = Selector('#preferred-interface');
  const interfaceOption = interfaceSelect.find('option');

  await user
    .typeText('#developer-name', 'Sourav')
    .click('#remote-testing')
    .click(interfaceSelect)
    .click(interfaceOption.withText('Both'))
    .expect(interfaceSelect.value)
    .eql('Both')
    .click('#submit-button')
    .expect(Selector('#article-header').innerText)
    .eql('Thank you, Sourav!');
});
```

### Command
`testcafe "browserstack:Samsung Galaxy S20 Ultra" ./testcafe_ssl.js  --ssl server.cert --hostname bs-local.com`

### Error
The session should have opened up an `https` url, but it's opening `http`. Image attached
<img width="1440" alt="TestcafeBSHttpsNotWorking" src="https://user-images.githubusercontent.com/95743457/156117748-bc867078-aec9-486d-b07c-6c1b0cc7a0c3.png">


While I tried to run the same on local, it opens up `https` url

**Command**
`testcafe chrome ./testcafe_ssl.js  --ssl server.cert --hostname bs-local.com`

**Screenshot** (ignore the page not loading error)

<img width="1440" alt="TestcafeLocalHttpsWorking" src="https://user-images.githubusercontent.com/95743457/156118382-3eb40852-b7f0-4016-bc6d-60a7d1d51663.png">

**Comment by chiragshah-bs** [comment]
@felis2803 sorry for the delay, can you please reopen this issue. I've added the details in the comment above

**Comment by alexphilin** [comment]
For team: The issue occurred due to a hardcoded `http` protocol [here](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/466ded007f965e4478ca3c954c7360a87c299806/src/browser-proxy.js#L21).
