### ISSUE TITLE
Proxy automate api

### ISSUE THREAD

**Issue by benquinteros** [DevExpress/testcafe-browser-provider-browserstack#164]
Are we able to proxy the automate api found 

https://www.browserstack.com/docs/automate/api-reference/selenium/browser#get-browser-list

it would be quite useful to take advantage of the latest/beta tags for a browser, currently at the moment you have to know the exact version e.g `"browserstack:firefox@99.0 beta:OS X Catalina"`

<img width="840" alt="Screen Shot 2022-04-07 at 1 27 53 pm" src="https://user-images.githubusercontent.com/11510971/162114357-8dd87152-cc4d-42ae-8bb6-304df33487f0.png">

Cheers

**Comment by felis2803** [comment]
Hello @benquinteros,

The version is optional. If you specify a browser without its version, e.g., `browserstack:firefox:OS X Monterey`, then the latest non-beta version will be used. Anyway, thank you for pointing that out.

**Comment by benquinteros** [comment]
Thanks @felis2803 ! 

Are we able to use the beta tag like so `browserstack:firefox@beta:OS X Monterey`

**Comment by felis2803** [comment]
At present, it's not possible to get the beta version this way. We have this issue: [https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/140](https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/140).
If this feature is important to you, you can try to implement it yourself and make a PR. Or you can wait for our implementation, but I cannot give you an estimated time frame.
