### ISSUE TITLE
npm audit shows vulnerability

### ISSUE THREAD

**Issue by stumueller** [DevExpress/testcafe-browser-provider-browserstack#171]
testcafe-browser-provider-browserstack is dependent on firefox-profile 0.1.1 - 4.0.0 which in turn is dependent on a vulnerable version of async

Newer versions of firefox-profile don't appear to be dependent on the vulnerable async. can we upgrade the version of firefox-profile?

**Comment by AndreyBelym** [comment]
Thank you for notifying us. I opened a PR that updates the problematic dependency: #172.

**Comment by Aleksey28** [comment]
Hi @altany,

Any personal estimate may be misleading, so currently I cannot give you a precise date. It will happen in the near future.

**Comment by AndreyBelym** [comment]
I apologize for the late response, `testcafe-browser-provider-browserstack@1.14.0` was published 6 days ago: https://github.com/DevExpress/testcafe-browser-provider-browserstack/releases/tag/v1.14.0
