### ISSUE TITLE
Security Vulnerability issue

### ISSUE THREAD

**Issue by alejandro-serrano** [DevExpress/testcafe-browser-provider-browserstack#173]
Hi,

We are getting the following security vulnerability issue in the plugin when performing a `yarn audit`:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Infinite loop in jpeg-js                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jpeg-js                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.4.4                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ testcafe-browser-provider-browserstack                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ testcafe-browser-provider-browserstack > jimp > @jimp/types  │
│               │ > @jimp/jpeg > jpeg-js                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1075625                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

Further information can be found here:
https://github.com/advisories/GHSA-xvf7-4v9q-58w6

Thanks!

**Comment by AlexKamaev** [comment]
Thank you for pointing this out to us. It looks like the `jimp` module is not under active development, so the maintainer cannot merge the PRs that fix the issue:
[https://github.com/oliver-moran/jimp/pull/1090](https://github.com/oliver-moran/jimp/pull/1090)
[https://github.com/oliver-moran/jimp/pull/1093](https://github.com/oliver-moran/jimp/pull/1093)
We'll take a look at this problem as soon as possible and will find an appropriate solution.

**Comment by kukhariev** [comment]
https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/9cfdb6f03c1bd39fcb0c5132fddc7a06afc411a3/src/backends/js-testing.js#L114-L119

What is the purpose of the `jimp` used here ?

It does the same thing:

```js
await fs.promises.writeFile(screenshotPath, buffer);
```

**Comment by Aleksey28** [comment]
It reads and writes images. We are already working on this issue and we will resolve it as soon as possible.
