### ISSUE TITLE
Support of the BROWSERSTACK_BUILD_NAME environment variable

### ISSUE THREAD

**Issue by kukhariev** [DevExpress/testcafe-browser-provider-browserstack#174]
[browserstack/github-actions/setup-env](https://github.com/browserstack/github-actions/tree/master/setup-env#setup-env) uses `BROWSERSTACK_BUILD_NAME` to set the build name.  It would be nice to add support for this variable in addition to `BROWSERSTACK_BUILD_ID`

**Comment by miherlosev** [comment]
Hi @kukhariev,

Thank you for pointing out this feature. If it's important for you, the PR is greatly appreciated.
