### ISSUE TITLE
Running `testcafe` with a lot of browsers crashes BrowserStack

### ISSUE THREAD

**Issue by maoberlehner** [DevExpress/testcafe-browser-provider-browserstack#18]
Hello, first of all thank you for this package – provided I'm testing with just a few browsers, it works great.

But the thing is, I want to test my project in all relevant browsers. The command I'm running looks like this:

```bash
testcafe 'browserstack:ie@10.0:Windows 8,browserstack:ie@11.0:Windows 10,browserstack:edge@15.0:Windows 10,browserstack:edge@14.0:Windows 10,browserstack:firefox@54.0:Windows 10,browserstack:firefox@55.0:Windows 10,browserstack:chrome@59.0:Windows 10,browserstack:chrome@60.0:Windows 10,browserstack:opera@46.0:Windows 10,browserstack:opera@47.0:Windows 10,browserstack:safari@9.1:OS X El Capitan,browserstack:safari@10.1:OS X Sierra' test/acceptance/ --app 'http-server demo/ -p 6666 -s'
```

What happens is, that it takes a really long time (about 6-10 Minutes) and after that TestCafe fails with the following error message:

```bash
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```

Going to the BrowserStack Automate dashboard, I can see, that the test instances were started but basically crashed or something similar. The spinners you can see in the screenshot keep spinning for many hours until after a day or something like that, the tests fail and only then I can start new tests.

![image](https://user-images.githubusercontent.com/6883314/30003953-83ac0ba2-90c6-11e7-952e-1fad94e8c1b8.png)

I'm not quite sure if this is a bug or if it works as intended. Basically I'm on a rather limited plan which is only allowed to run one test at a time. So this might be the expected behavior if somebody starts a bunch of tests simultaneously?

Also this might very likely be not a problem with this package (alone) but on the side of BrowserStack – in this case I hope we can let this issue open and work together with https://github.com/browserstack to work on a solution for this problem.

The expected behavior in my opinion is, that when starting more tests than allowed, they are not started simultaneously but consecutively.

Thanks in advance.

**Comment by maoberlehner** [comment]
I came up with a little workaround for this problem:

```bash
#!/bin/bash

browsers=( "browserstack:ie@10.0:Windows 8" "browserstack:ie@11.0:Windows 10" "browserstack:edge@15.0:Windows 10" "browserstack:edge@14.0:Windows 10" "browserstack:firefox@54.0:Windows 10" "browserstack:firefox@55.0:Windows 10" "browserstack:chrome@59.0:Windows 10" "browserstack:chrome@60.0:Windows 10" "browserstack:opera@46.0:Windows 10" "browserstack:opera@47.0:Windows 10" "browserstack:safari@9.1:OS X El Capitan" "browserstack:safari@10.1:OS X Sierra" )

for i in "${browsers[@]}"
do
	./node_modules/.bin/testcafe "${i}" test/acceptance/
done
```

I trigger a new TestCafe command for every browser I want to test – it works but it is a rather meh solution.

**Comment by AndreyBelym** [comment]
Hello @maoberlehner! TestCafe expects that all specified browsers will be connected, so it will report error when you are trying to start a lot of browsers but have only one Browserstack worker, Your solution is a correct way to overcome this.

**Comment by maoberlehner** [comment]
Thank you for your answer @AndreyBelym – I guess than the only problem is that BrowserStack is crashing and blocking further tests for several hours but I guess this has nothing to do with TestCafe or this provider.

Thank you for your work on this great project.

**Comment by Jing19** [comment]
Hi all, why I am still facing the same connection issue by only running one browser?
Running my tests with a command:
`> testcafe 'browserstack:chrome@60.0:Windows 10' -e src/test/**/*.js`
After 6 minutes, I get following error:
`ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.`

Thanks in advance.

**Comment by guptaakhil** [comment]
@maoberlehner, @AndreyBelym  : I am facing same issue, please do let us know how can i resolve this in windows only.

**Comment by kaitmore** [comment]
For anyone interested, this is how I solved it. I used the browserstack node client to check how many sessions are running.

```javascript 
const createTestCafe = require("testcafe");
const glob = require("glob-promise");
const BrowserStack = require("browserstack");

// Each sub array defines a batch of browserstack workers.
// Our current plan allows for a max of 5 workers at a time,
// so to avoid crashing browserstack we group our browsers
// into 2 batches that run will run consecutively.
const SUPPORTED_BROWSERS = [
  [
    "browserstack:safari@11.0:OS X High Sierra",
    "browserstack:safari@10.1:OS X Sierra",
    "browserstack:edge@16.0:Windows 10",
    "browserstack:edge@15.0:Windows 10",
    "browserstack:ie@11.0:Windows 10"
  ],
  [
    "browserstack:chrome@64.0:OS X High Sierra",
    "browserstack:chrome@63.0:OS X High Sierra",
    "browserstack:firefox@58.0:OS X High Sierra",
    "browserstack:firefox@57.0:OS X High Sierra"
  ]
];

const browserStackCredentials = {
  username: process.env.BROWSERSTACK_USERNAME,
  password: process.env.BROWSERSTACK_PASSWORD
};

async function getFiles(globPattern) {
  return await glob(globPattern)
    .then(files => files)
    .catch(e => console.error(e));
}

async function getRunningBrowserstackSessions() {
  const client = BrowserStack.createClient(browserStackCredentials);
  const workerStatus = await new Promise(function(resolve, reject) {
    client.getApiStatus((error, workers) => {
      if (error) reject(error);
      else resolve(workers);
    });
  });
  return workerStatus;
}

async function createTestCafeInstance(browser, files) {
  let testcafe;
  await createTestCafe()
    .then(tc => {
      testcafe = tc;
      return tc
        .createRunner()
        .startApp("npm start")
        .src(files)
        .browsers(browser)
        .run();
    })
    .then(failedCount => {
      console.log("Tests failed: " + failedCount);
      testcafe.close();
    })
    .catch(err => console.error(err));
}

async function startTests(browsers, createTestCafeInstance) {
  // The testcafe node api does not accept glob patterns, so grab relevant test files using node-glob
  let files = await getFiles("e2e-tests/tests/*.js");
  // Check that there are no tests already running
  let sessionInfo = await getRunningBrowserstackSessions();
  if (sessionInfo.running_sessions !== 0) {
    console.error(
      "There are not enough available Browserstack workers to run these tests. Please cancel any running sessions from the Browserstack Automate dashboard and try again."
    );
  } else {
    // Create a new testcafe instance for each batch of browsers
    for (let i = 0; i < browsers.length; i++) {
      await createTestCafeInstance(browsers[i], files);
    }
  }
}

startTests(SUPPORTED_BROWSERS, createTestCafeInstance);
```

**Comment by guptaakhil** [comment]
is it working for you, this is not working for me.

**Comment by Kryshtopenko** [comment]
> For anyone interested, this is how I solved it. I used the browserstack node client to check how many sessions are running.
> 
> ```js
> const createTestCafe = require("testcafe");
> const glob = require("glob-promise");
> const BrowserStack = require("browserstack");
> 
> // Each sub array defines a batch of browserstack workers.
> // Our current plan allows for a max of 5 workers at a time,
> // so to avoid crashing browserstack we group our browsers
> // into 2 batches that run will run consecutively.
> const SUPPORTED_BROWSERS = [
>   [
>     "browserstack:safari@11.0:OS X High Sierra",
>     "browserstack:safari@10.1:OS X Sierra",
>     "browserstack:edge@16.0:Windows 10",
>     "browserstack:edge@15.0:Windows 10",
>     "browserstack:ie@11.0:Windows 10"
>   ],
>   [
>     "browserstack:chrome@64.0:OS X High Sierra",
>     "browserstack:chrome@63.0:OS X High Sierra",
>     "browserstack:firefox@58.0:OS X High Sierra",
>     "browserstack:firefox@57.0:OS X High Sierra"
>   ]
> ];
> 
> const browserStackCredentials = {
>   username: process.env.BROWSERSTACK_USERNAME,
>   password: process.env.BROWSERSTACK_PASSWORD
> };
> 
> async function getFiles(globPattern) {
>   return await glob(globPattern)
>     .then(files => files)
>     .catch(e => console.error(e));
> }
> 
> async function getRunningBrowserstackSessions() {
>   const client = BrowserStack.createClient(browserStackCredentials);
>   const workerStatus = await new Promise(function(resolve, reject) {
>     client.getApiStatus((error, workers) => {
>       if (error) reject(error);
>       else resolve(workers);
>     });
>   });
>   return workerStatus;
> }
> 
> async function createTestCafeInstance(browser, files) {
>   let testcafe;
>   await createTestCafe()
>     .then(tc => {
>       testcafe = tc;
>       return tc
>         .createRunner()
>         .startApp("npm start")
>         .src(files)
>         .browsers(browser)
>         .run();
>     })
>     .then(failedCount => {
>       console.log("Tests failed: " + failedCount);
>       testcafe.close();
>     })
>     .catch(err => console.error(err));
> }
> 
> async function startTests(browsers, createTestCafeInstance) {
>   // The testcafe node api does not accept glob patterns, so grab relevant test files using node-glob
>   let files = await getFiles("e2e-tests/tests/*.js");
>   // Check that there are no tests already running
>   let sessionInfo = await getRunningBrowserstackSessions();
>   if (sessionInfo.running_sessions !== 0) {
>     console.error(
>       "There are not enough available Browserstack workers to run these tests. Please cancel any running sessions from the Browserstack Automate dashboard and try again."
>     );
>   } else {
>     // Create a new testcafe instance for each batch of browsers
>     for (let i = 0; i < browsers.length; i++) {
>       await createTestCafeInstance(browsers[i], files);
>     }
>   }
> }
> 
> startTests(SUPPORTED_BROWSERS, createTestCafeInstance);
> ```

don't forget to install dotenv because executing node thisScript.ts it doesn't recognize ENV variables (in your case):
``` > const browserStackCredentials = {
>  username: process.env.BROWSERSTACK_USERNAME,
>  password: process.env.BROWSERSTACK_PASSWORD
