### ISSUE TITLE
The latest executable does not seem to work

### ISSUE THREAD

**Issue by rajathrao** [DevExpress/testcafe-browser-provider-browserstack#187]
https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip  the executable has a issue .Does not connect to BrowserStack. It times out after sometime. Earlier Executable which I had downloaded a week ago I had no issues,

**Comment by AlexKamaev** [comment]
I believe this issue is related to the BrowserStack Local executable, but not to TestCafe, so it's better to address the issue directly to the BrowserStack team.
