### ISSUE TITLE
Migrate to Browserstack SDK

### ISSUE THREAD

**Issue by eisenreich** [DevExpress/testcafe-browser-provider-browserstack#191]
Does it make sense to migrate this lib to the new Browserstack SDK?

https://www.browserstack.com/blog/introducing-browserstack-sdk/

**Comment by aleks-pro** [comment]
It's not clear to me what you mean by "migrate this lib to the new Browserstack SDK". It would be nice if the Browserstack SDK had support for TestCafe tests out of the box. I believe that this is technically possible, but this issue should be addressed on the Browserstack team’s side.
