### ISSUE TITLE
``firefox-profile`` dep needs an update

### ISSUE THREAD

**Issue by cieniawska** [DevExpress/testcafe-browser-provider-browserstack#192]
Hi, is there a possibility to upgrade the ``firefox-profile`` package to ``v4.2.2``? 

It seems that these versions: ``0.4.3 - 4.0.0`` are dependent on ``async`` package  < v 2.6.4 and there's a [vulnerability detected by gh](https://github.com/advisories/GHSA-fwr7-v2mv-hh25).

**Comment by AlexKamaev** [comment]
Thank you for reporting this to us. We'll check it.
