### ISSUE TITLE
``request-promise`` requires acction

### ISSUE THREAD

**Issue by cieniawska** [DevExpress/testcafe-browser-provider-browserstack#194]
Hello,

it seems that the package you're using is deprecated.

<img width="1236" alt="Screenshot 2023-03-20 at 05 59 57" src="https://user-images.githubusercontent.com/95585601/226268989-be7686f6-befd-4017-b9b7-8aff49ec5d57.png">

Cheers,
Kasia

**Comment by Aleksey28** [comment]
Hi @cieniawska.

Thank you for noticing this. If it's essential to you, please create a PR with a replaced `request-promise` module. We appreciate your help.

**Comment by aleks-pro** [comment]
Release [v1.15.0](https://github.com/DevExpress/testcafe-browser-provider-browserstack/releases/tag/v1.15.0) addresses this.

Thanks to @kelnei for his contribution.
