### ISSUE TITLE
add support for --native automation with testcafe-browser-provider-browserstack plugin

### ISSUE THREAD

**Issue by agrawalsaurabhs** [DevExpress/testcafe-browser-provider-browserstack#198]
When we try to run a test build on BrowserStack with --native automation and TestCafe version 2.5.0, we get the following error:

`ERROR: The following browser(s) do not support the Native Automation mode: “BrowserStack”.`

With version 2.5, Test Cafe now allows users to run tests using CDP rather than the previous hammerhead approach. To support this use case on BrowserStack, Test Cafe must add this support to the testcafe-browser-provider-browserstack. This would be applicable for other cloud providers as well.

**Comment by AlexKamaev** [comment]
Thank you for reaching out to us. Currently, we are focused on developing the Native Automation mode for local Chromium-based browsers. We do not have plans to support cloud-based browsers in the nearest future.
