### ISSUE TITLE
Add config option to support native automation

### ISSUE THREAD

**Issue by patrickathompson** [DevExpress/testcafe-browser-provider-browserstack#199]
When running latest version of TestCafe with nativeAutomation enabled and using browserstack remote browser provider, the following error occurs:

_Error: The "browserstack" do not support the Native Automation mode. Remove the "native automation" option to continue._

Please add a configuration option to support this new mode, or release a new module that supports it.

Thanks!

**Comment by AlexKamaev** [comment]
Hello,

At present, TestCafe supports the Native Automation mode only for local Chromium-based browsers. Please refer to the following help topic to learn more about Native Automation mode limitations: [https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode#limitations](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode#limitations).

**Comment by patrickathompson** [comment]
This is a new feature request. Are you saying that you are not going to support native automation in remote browsers moving forward? If you plan on supporting this feature then you should probably leave the issue open.

**Comment by AlexKamaev** [comment]
duplicate of https://github.com/DevExpress/testcafe/issues/7715
