### ISSUE TITLE
IE 11 hangs with pending proxy requests

### ISSUE THREAD

**Issue by benlind** [DevExpress/testcafe-browser-provider-browserstack#200]
I am attempting to test my site (https://payment-express.net/) in IE 11. When you visit that URL, you should be auto-redirected to a login screen.

When I try to run this test in IE 11 via BrowserStack, the test hangs. If I use the "local testing" BrowserStack feature with `testcafe remote` and open the IE 11 network console before visiting the site, I always see some requests to various assets that hang in the "pending" status. A common one is `transport-worker.js`:

<img width="1813" alt="Screenshot 2023-05-26 at 10 42 00 AM" src="https://github.com/DevExpress/testcafe-browser-provider-browserstack/assets/180348/8e127eeb-0806-4682-bf56-178ecbbed864">

Specifically, this line is hanging:

<img width="1171" alt="Screenshot 2023-05-26 at 10 41 56 AM" src="https://github.com/DevExpress/testcafe-browser-provider-browserstack/assets/180348/a993ab53-d39f-42c9-b35a-ba07b98ecac8">

I have also seen other assets hang (like a large JS bundle file).

We already reached out to BrowserStack about this and they said that this is not an issue on their end, since you can manually perform the same redirect successfully via the Live tool.

I have seen a similar issue in the past with the hammerhead proxy, where files above a certain size can't be proxied and hang. Could this be related?

Here is a reproduction repo: https://github.com/benlind/testcafe-browserstack-ie11-repro

**Comment by miherlosev** [comment]
Hi @benlind,

We decided to remove IE11 support in the next major version due to extremely low usage in the community. Please consider other tools to run tests with IE11.
