### ISSUE TITLE
Running the BrowserStack provider on Windows creates NUL file

### ISSUE THREAD

**Issue by berendhaan** [DevExpress/testcafe-browser-provider-browserstack#24]
When you run TestCafe using the BrowserStack provder it creates a file which you cannot delete in Windows.
It looks like the implementation tries to pass in the NUL device to the local BrowserStack runner to silently run and not produce errors. But instead of not creating a log file it's creates a file with the name NUL.

As you can see in the config it passes NUL to the logfile option.
`var opts = {
            ...
            logfile:         OS.win ? 'NUL' : '/dev/null',
            ...
};` [Source](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/bfe71c3e193a85841e725527a1bc6feb77d995eb/src/index.js#L82)

This line translates to `BrowserStackLocal.exe --log-file NUL`. When you run this command in Windows you also get the NUL file created on the disk.

Since this provider uses `browserstack-local` as a dependency to call `BrowserStackLocal.exe` I'm not sure what the best way is to fix this issue. A quick fix will be to just pass JavaScript null to the config so it creates a default logfile.

**Comment by AndreyBelym** [comment]
Hello @berendhaan! 

It's known problem, and it must be fixed by PR #23. Provider will create logfile in a temporary directory on Windows. By default logfile is created in the current working directory, which is not good, because you have to add logfile to `.gitignore` to prevent accidentally addition to VCS.

**Comment by berendhaan** [comment]
That sounds good 👍  Do you have any idea when the PR will be merges to the mainline?

**Comment by AndreyBelym** [comment]
I hope to finish it today, but it can take up to a couple of days for approving & merging.

**Comment by AndreyBelym** [comment]
Fixed in `1.4.0`
