### ISSUE TITLE
Browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

### ISSUE THREAD

**Issue by guptaakhil** [DevExpress/testcafe-browser-provider-browserstack#25]
Hi @andrewtelnov,@maoberlehner ,  @AlexanderMoskovkin 

I am executing my script in IE ,mac and android and getting this error "browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues" most of the time during parallel run in BrowserStack. 

My License is quite capable to run n no. instance and it's workk fine for chrome,firefox for windows. 

My Application use http-authentication, i used http-auth npm module which eaisly by pass for chrome  or firefox  but not for mac(safari), ie. 

please suggest here , how can i do parallel with all device combimation.

Any help will really appreciate
.

**Comment by guptaakhil** [comment]
any update guys on this ??

**Comment by AndreyBelym** [comment]
Hi @guptaakhil, if you use `localhost` as a testing hostname, try to use 127.0.0.1 or your Network IP, as suggested in [this article](https://www.browserstack.com/question/663). Also, try to use ports from [this list](https://www.browserstack.com/question/664) for testing. You can specify it usng the [ports](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--ports-port1port2).

@Timywitt, I've reproduced the problem with some Android browsers (`Google Pixel`, `Samsung Galaxy S8`) . I'm investigating the problem right now. However, `Google Nexus 6`  works for me, have you tried to run it?

**Comment by Timywitt** [comment]
Google Nexus 6 works for me as well. Even though this is not the solution, thank you very much for finding this out :)

**Comment by Timywitt** [comment]
As far as I can tell, these Android devices are the only ones that work:

- Samsung Galaxy S6, 5.0
- Google Nexus 6, 6.0
- Samsung Galaxy Note 4, 6.0

**Comment by guptaakhil** [comment]
@Timywitt @AndreyBelym : this solution is not working for me , Browser becom unresponsive while we running parallel run in ff and chrome

**Comment by adaher15** [comment]
Hello
I am facing the same issue on Chrome / Mac. The test was running properly until I click on one link that redirect the browser to another page and after a long wait, I got the error:
`ERROR The Chrome 73.0.3683 / Mac OS X 10.13.6 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`

I can assure that there is no network issue in this case, it's something to do with the way the controller manage the driver.

**Comment by AndreyBelym** [comment]
@Esteban26, TestCafe doesn't support Chrome versions below Chrome 59,

@adaher15, please try to reproduce the issue on a local machine without BrowserStack, submit a new bug report to the TestCafe repository and provide an example: [New Issue: Bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md).

**Comment by owen-m1** [comment]
May be same as https://github.com/DevExpress/testcafe/issues/2480
