### ISSUE TITLE
(node:13052) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): [object Object] or 

### ISSUE THREAD

**Issue by guptaakhil** [DevExpress/testcafe-browser-provider-browserstack#26]
Hi Team, 

I am getting error in testcafe while we run multiple device combination in Browser Stack. It works fine when run with Single Thread for small  execution but failing forLong run.  we are using native testcafe Browser Stack plugin. 

 after some time this error comes : This problem may appear when a browser hangs or is closed, or due to network issues.

**Comment by guptaakhil** [comment]
Any udpate Guys on this??

**Comment by AndreyBelym** [comment]
Unfortunately I need access to your test suite to reproduce the problem. Please note, that maximum BrowserStack session can't be longer than 30 minutes for JS testing API and 2 hours for Automated API.

**Comment by guptaakhil** [comment]
Hi @AndreyBelym : this issue is not getting resolve with testcafe-browser-stackplugin.  I have open new  issue for firefox : https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/42. it's working fine in chrome only.

**Comment by AndreyBelym** [comment]
I close this issue due to a long period of inactivity, Please reopen the issue if you still can reproduce the problem with the latest `testcafe-browser-provider-browserstack`.
