### ISSUE TITLE
Running tests on Jenkins: TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by Lukas-Kullmann** [DevExpress/testcafe-browser-provider-browserstack#27]
When running our tests on our Jenkins, I get an error

    /var/lib/****/node_modules/browserstack-local/lib/Local.js:61
              callback(new LocalError(data['message']['message']));
                                                     ^
    
    TypeError: Cannot read property 'message' of undefined
        at /var/lib/****/node_modules/browserstack-local/lib/Local.js:61:50
        at ChildProcess.exithandler (child_process.js:267:7)
        at emitTwo (events.js:126:13)
        at ChildProcess.emit (events.js:214:7)
        at maybeClose (internal/child_process.js:925:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

The issue here is, that the response of the `childProcess.execFile` in the `browserstack-local` package is empty. `error` is `null` and `stdout` and `stderr` are both empty strings. That's why `data` is an empty object.

I tried investigating what is going on, but I did not find a solution.

The binaryArgs for our run were:

    [ '--daemon',
      'start',
      '--log-file',
      '/dev/null',
      '--key',
      '****',
      '--local-identifier',
      1523874577640,
      '--enable-logging-for-api' ]

If I try to provide a logfile, it will be empty.

We do not use a proxy.

If I run the tests locally on my machine (with the same credentials), I do not get an error. The tests start normally.

Did anybody ever have a similar issue or does anybody have an idea what might be going on? Any help would be appreciated!

**Comment by AndreyBelym** [comment]
Hi @Lukas-Kullmann! Looks like it's a problem with [browserstack-local-nodejs](https://github.com/browserstack/browserstack-local-nodejs/) package. I would recommend you to create an issue there. 

For debugging purposes, I suggest you to check exit code of the Browserstack Local process, if it's not zero, likely it's a problem with permissions or something, check if binary at `$HOME/.browserstack/BrowserStackLocal` has executable flag. If it won't help, try to connect to your Jenkins slave after all packages have been installed, and invoke `BrowserStackLocal` binary manually.

**Comment by Lukas-Kullmann** [comment]
Hi @AndreyBelym! Thanks for the response!
We actually could nail the proplem down. We actually need to set the `parallel-runs` flag to some value to be able to start the server. Currently this is not possible with this provider.

I will fix it and open a PR. :)

**Comment by AndreyBelym** [comment]
That's interesting. Sorry to cast you @pulkitsharma07, but could you please clarify if it is required to use this flag when running multiple builds, or I should contact the Browserstack Support for that? It's my shame that I've missed that flag, but everything was working fine for us before. The flag affects a number of `BrowserStackLocal` forked process, and judging by different flag's values, `BrowserStackLocal` might spawn up to spawns `($PARALLEL_RUNS - 1) / 10`, handicapped with 9 processes in total. So looks like the default value for `--parallel-runs` can be any number starting from  `31` and ending with `40`.

**Comment by AndreyBelym** [comment]
@Lukas-Kullmann I've published `testcafe-browser-provider-browserstack@1.3.0` with the fix, thank you so much! 🎉

**Comment by Lukas-Kullmann** [comment]
I thank you so much, that was super fast - lightning speed! :-)

**Comment by shermaneric** [comment]
Hey there.  I'm sorry to bump this old thread.   I'm running into a similar issue [here](https://stackoverflow.com/questions/51546081/testcafe-cannot-read-property-message-of-undefined).  Not sure if I'm doing something grossly wrong.  Thanks!

**Comment by AndreyBelym** [comment]
Hi @shermaneric, have you tried to set the `BROWSERSTACK_PARALLEL_RUNS` environment variable?

**Comment by shermaneric** [comment]
Indeed.  Here's the [SO post](https://stackoverflow.com/questions/51546081/testcafe-cannot-read-property-message-of-undefined?noredirect=1#comment90080954_51546081).  I'm attempting to run it out of the node alpine-7 container.  Probably something limiting me there perhaps? 

Thanks for the quick response!
