### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by FDiskas** [DevExpress/testcafe-browser-provider-browserstack#32]
There is missing "resize" ability. Or at least it's not working.
Documentation http://devexpress.github.io/testcafe/documentation/test-api/actions/resize-window.html

**Comment by AndreyBelym** [comment]
Hi @FDiskas, resizing is implemented in `testcafe-browser-provider-browserstack@1.4.0` for Browserstack Automate API. Please, update the provider and set the `BROWSERSTACK_USE_AUTOMATE` to 1. If resizing still won't work after these steps, feel free to reopen the issue.
