### ISSUE TITLE
Problem running test in Jenkins CI

### ISSUE THREAD

**Issue by dgieselaar** [DevExpress/testcafe-browser-provider-browserstack#41]
Hi,

Basically re-opening this issue: https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/14#issue-234146535

We have the same issue. The debug build (`1.1.1-git.201706070945`) fixes it, but we'd like to upgrade to the latest version of the provider for better reporting.

**Comment by AndreyBelym** [comment]
Hi @dgieselaar, that build was a very dirty fix. I just disabled closing of Browserstack tunnels after a test session, so it can't be used in production. Because I can't reproduce this behavior, I don't know what can I do to fix it. 

I guess if I could disable automatic tunnel creation and termination, it could work for such cases, but you would have to create a tunnel using `browserstacklocal` manually.

**Comment by dgieselaar** [comment]
What is the downside of this build? For us it's working fine, but I might have missed something. What particular lines need to be changed? I cannot find the source for the debug version. If I know where to look I can probably add some debugging statements that will help me fix it.

**Comment by dgieselaar** [comment]
Ah, it keeps the browserstack-local process open. I found various (possibly) related issues:
- https://github.com/browserstack/browserstack-local-nodejs/issues/25
- https://github.com/browserstack/browserstack-local-nodejs/issues/41

etc.

Would you be open to a PR that accepts a env variable (`BROWSERSTACK_KILL_CONNECTOR`) that will just kill the process (by using `connectorInstance.pid`) when the tests complete?

**Comment by AndreyBelym** [comment]
Thanks @dgieselaar, I think it's better to kill process if it doesn't close gracefully after some time. I think, 10 seconds must be enough for the timeout.

**Comment by dgieselaar** [comment]
@AndreyBelym Alright, would you want that (the killing of the process) in this library, or is it something that you think should be handled outside of this library?

**Comment by AndreyBelym** [comment]
@dgieselaar yes, it must be implemented in the provider. It would be perfect if you could make a PR 😄

**Comment by dgieselaar** [comment]
Will do!
