### ISSUE TITLE
BrowserStack: Parallel run Issue in Firefox and Chrome

### ISSUE THREAD

**Issue by guptaakhil** [DevExpress/testcafe-browser-provider-browserstack#42]
Hi All, 

I am using testcafe-browser-provider-browserstack plugin to connect for execution in cloud and running my scripts into chrome and firefox and using node version v8. 

Here we have analyse the weired behaviour of execution in ff, page getting refresh automatically after login. Scripts enter credential and land to home page and it's revert back to sign in page. It's working fine in chrome and other Browser. 

In local execution in ff working as expected , not sure this in plugin issue or BrowserStack. kindly do reply. 

Also, In bunch run in chrome and ff most of scripts is fail while indivdual run it got passed.  
@AndreyBelym @AlexanderMoskovkin  : kindly do let me know if it is existing issue in testcafe

**Comment by AndreyBelym** [comment]
Hi @guptaakhil, unfortunately I can't reproduce it without your page.

**Comment by AndreyBelym** [comment]
I close this issue due to a long period of inactivity, Please reopen the issue if you still can reproduce the problem with the latest `testcafe-browser-provider-browserstack`.
