### ISSUE TITLE
Don't run mobile device tests on real device

### ISSUE THREAD

**Issue by xar** [DevExpress/testcafe-browser-provider-browserstack#43]
When I use some of mobile devices from the list which `testcafe -b browserstack` generates. I get an error saying `Was unable to open the browser "browserstack:iPhone SE@11.2" due to error. ...You can upgrade to the Automate Mobile plan to test on real devices.` . Which is correct but I know that browserstack has an option to disable real device testing and instead of that run It in simulator(As par of normal Automate plan). How this option can be applied via testcafe?

**Comment by AndreyBelym** [comment]
AFAIR there was some choice between real devices and emulators some time ago, but now there is no such option, there are just two kinds of device configurations on BrowserStack. In [this list](https://www.browserstack.com/list-of-browsers-and-platforms?product=js_testing) real devices have blue phone icon, devices without icon are emulators. You'll get an error if you try to request a configuration of a real device without setting the `real_mobile` flag to `true`. You could add a line [here](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/master/src/index.js#L166) to override this flag with `false` value and get an error that required device configuration is not available.
