### ISSUE TITLE
Fixture page url prepended with local external ip

### ISSUE THREAD

**Issue by jamesbrattBoomi** [DevExpress/testcafe-browser-provider-browserstack#45]
Hi,
Have just been trying to get something up and running with a very basic testcafe implementation, whereby testcafe navigates to https://google.com and performs a basic assertion.
When the test runs in browserstack, I can see that it in fact navigates to:

< my external ip address >:< some port >/gHjFdf/https://google.com

I have not set any of the proxy options env variables (as I assumed I would not need them).
Is this the expected behaviour?

Many thanks,
James

**Comment by AndreyBelym** [comment]
Hi @jamesbrattBoomi, TestCafe uses the [testcafe-hammerhead](https://github.com/DevExpress/testcafe-hammerhead) URL-rewriting proxy under the hood, that's why a test URL is actually served from your IP address. It's the expected behavior.
