### ISSUE TITLE
Testing on mobile devices returns an error

### ISSUE THREAD

**Issue by chinjon** [DevExpress/testcafe-browser-provider-browserstack#47]
I've been testing out this package with a trial BrowserStack account, so lack of access to devices might be the reason for this issue.

Most of the android devices available to use with the trial account are marked as _real devices_ and therefore I am under the assumption they are.

My command: `testcafe "browserstack:Samsung Galaxy Tab 4 10.1@4.4" <TEST_FILE>`

I've been trying to run tests with those devices but an error message with a status code of 403 was returned:
`
StatusCodeError: 403 - {
"message":"We're sorry, but we no longer support emulators or simulators. However, you can now run your selenium tests on real iOS and Android devices. Real devices are faster and more stable. Please contact our Sales team by visiting https://www.browserstack.com/contact and creating a query related to Sales.","errors":[]}
`

Unsure if there has been a change in their API and that there needs to be an indication to use a _real device_.

**Comment by kenf128** [comment]
we run across the same problem!

**Comment by Lukas-Kullmann** [comment]
Have you tried to set `BROWSERSTACK_USE_AUTOMATE` to `1`?

**Comment by AndreyBelym** [comment]
Hi @chinjon, @kenf128, @Lukas-Kullmann, Browserstack removed support of running tests on device emulators judging by their [Browsers & Mobile Devices](https://www.browserstack.com/list-of-browsers-and-platforms?product=js_testing) page, but forgot to update devices list returned by the [JS testing API endpoint](https://github.com/browserstack/api#getting-available-browsers). Use [Browsers & Mobile Devices](https://www.browserstack.com/list-of-browsers-and-platforms?product=js_testing) to choose a supported device, or set the `BROWSERSTACK_USE_AUTOMATE` environment variable to 1 and run `testcafe -b browserstack` to get the list of supported devices in CLI.

I will contact Browserstack Support team to inform them of JS testing API inconsistency.

**Comment by chrismbarr** [comment]
For future googlers that run across this thread, try adding the `real_mobile: true` option

Related: https://github.com/browserstack/browserstack-runner/issues/196
