### ISSUE TITLE
Error in binary downloading request

### ISSUE THREAD

**Issue by darlanmendonca** [DevExpress/testcafe-browser-provider-browserstack#5]
Hey guys, I'm starting with testcafe and browserstack. 
I can implement all, and test things in multiples browsers, locally. But on try run in browserstackI found the an error, and I really dont have idea of what is

the error is the following, when I run my script `npm test`

![screen shot 2017-03-16 at 17 08 41](https://cloud.githubusercontent.com/assets/876227/24016508/2928fe06-0a6b-11e7-8f54-39207a25e173.png)

my script test is a file in sh

```sh
#!/bin/bash

set -e

./node_modules/.bin/testcafe browserstack:Chrome \
./sources/scripts/*.spec.js \
--app './node_modules/.bin/http-server . -s'
```

Another thing, I'm beghind a proxy, maybe be that.

You have an idea of what is that error?

**Comment by AndreyBelym** [comment]
Hello @darlanmendonca! The error occurred very early, before the tests was actually run? So maybe it's a problem with browserstack-local package, it downloads the BroserStackLocal binary at first usage: https://github.com/browserstack/browserstack-local-nodejs/blob/master/lib/LocalBinary.js#L73. Try to download it manually by links from here: https://github.com/browserstack/browserstack-local-nodejs/blob/master/lib/LocalBinary.js#L14, create `.browserstack` directory in your home dir (`/Users/$USER` on macOS, `/home/$USER` on Linux, `C:\Users\%USER%` on Windows), and put the binary in the created directory.

**Comment by darlanmendonca** [comment]
@AndreyBelym I download the file, and placed it on `~/.browserstack` but the problem continues :(

When I run test script, they try download again, almost with the bin already in  `~/.browserstack` (manually)

I will try debug the file [lib/LocalBinary.js](https://github.com/browserstack/browserstack-local-nodejs/blob/master/lib/LocalBinary.js)

**Comment by darlanmendonca** [comment]
Whose is the `browserstack-local-nodejs`? I found only` browserstack-local` in my node_modules

**Comment by darlanmendonca** [comment]
is the same, I think, I found the code now

**Comment by YacheLee** [comment]
```
npm uninstall testcafe-browser-provider-browserstack
npm install testcafe-browser-provider-browserstack

```

**Comment by AndreyBelym** [comment]
Closing it since it's a `browserstack-local` issue.
