### ISSUE TITLE
Suport for Network Logs

### ISSUE THREAD

**Issue by galegor** [DevExpress/testcafe-browser-provider-browserstack#52]
Hi!
Is it possible to use browserstack.networkLogs functionality described here:
https://www.browserstack.com/automate/debugging ??
Gregor

**Comment by AndreyBelym** [comment]
Hi @galegor, unfortunately it's not possible. I mark this question as enhancement, and it will be implemented in next releases.

**Comment by itszero** [comment]
Would a PR following the same pattern (environment variables) be useful? or is the team already have something in progress?

Thanks!

**Comment by AndreyBelym** [comment]
@itszero, it will be superior if you make a PR! I think we can introduce an environment variable to that will enable network logs capturing when it's defined.

**Comment by itszero** [comment]
Hey, FYI I created #54 for this request.

**Comment by itszero** [comment]
ping for review :)

**Comment by AndreyBelym** [comment]
Sorry for the delays, your PR is fine, I just need some time to find out what's wrong with the tests.

**Comment by pulkitsharma07** [comment]
@itszero : Look into the `BROWSERSTACK_USE_AUTOMATE` env variable.

**Comment by akratzel** [comment]
Any update here?
