### ISSUE TITLE
Use Device with specific browser

### ISSUE THREAD

**Issue by Exomnius** [DevExpress/testcafe-browser-provider-browserstack#53]
I'm trying to provide a device name and browser name through the browsers argument (using the runner class), but I cant seem to get the correct string format.

example: ''browserstack:iPhone 8:Safari". 
result: `Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.`

What is the correct format to specify a device AND browser. 

FYI: I'm using the BrowserStack Automate API.

Thanks in advance.

**Comment by AndreyBelym** [comment]
Sorry for the late answer, but it's not possible to use non-default browser on mobile devices with BrowserStack Automate. See https://www.browserstack.com/list-of-browsers-and-platforms?product=automate.
