### ISSUE TITLE
Need proxy configuration options

### ISSUE THREAD

**Issue by drobannx** [DevExpress/testcafe-browser-provider-browserstack#6]
I do not see any Browserstack configuration options to setup a proxy. I have a need for that due to network rules that do not allow communication between our internal network and Browserstack. Other applications we have get around this with Browserstack using an internal proxy and setting the appropriate configuration options. I'd be happy to submit a PR but I want to make sure the configuration is done correctly for this provider.

Thanks!

**Comment by AndreyBelym** [comment]
Hello @drobannx! We use Browserstack Local proxy, it creates a tunnel from your network to the Browserstack cloud, so if you are behind a firewall or NAT it should be sufficient. See Browserstack Local [use cases](https://www.browserstack.com/local-testing#configuration). But if you connect to the internet with your own corporate SOCKS or HTTP proxy, we have to implement additional options.

**Comment by drobannx** [comment]
@AndreyBelym Thanks for the response! The tunnel does work for me as I can hit the Browserstack cloud but the application that I am trying to test against cannot be reached outside our network due to an AWS WAF. We have an internal proxy that is whitelisted in the WAF so that any traffic going through it can hit the application. 

It sounds like there may be additional options needed for this use case or a piece that I am missing. If you could list what additional options need to be implemented, I'd be happy to take a stab at them and issue a PR.

**Comment by AndreyBelym** [comment]
There are two sets of proxy-related options for Browserstack Local: `proxy-host`, `proxy-port`, `proxy-user`. `proxy-pass` for proxy that handles Browserstack Local binary, and `local-proxy-host`, `local-proxy-port`, `local-proxy-user` and `local-proxy-pass` for proxy that handles the tested app. All their descriptions can be found in [this list](https://www.browserstack.com/local-testing#modifiers). 

In my view we can introduce two additional environment  variables (e.g. `BROWSERSTACK_PROXY` and `BROWSERSTACK_LOCAL_PROXY`) , and pass desired proxy configuration trough them in form `user:pass@host:port`. If we add some dummy protocol to that string, we will be able to use [url.parse](https://nodejs.org/api/url.html#url_url_strings_and_url_objects) to split proxy configuration into 4 required parts, and then pass these parts to Browserstack Local [here](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/91faa9493d1a824219fab2ec1d37df7fa1b856a3/src/index.js#L50). 

Of course if  you have some other ideas they are welcome in any form of dicussion or a PR. Also, I will really appreciate your help, but when you feel bored or tired, just let me know and I will implement it. 😄

**Comment by drobannx** [comment]
@AndreyBelym Working on this now. Should have something to you today :)

**Comment by drobannx** [comment]
@AndreyBelym I added a PR. Let me know if theres anything I need to add/change.
