### ISSUE TITLE
Update npm dependencies v1.5.0

### ISSUE THREAD

**Issue by izisfro** [DevExpress/testcafe-browser-provider-browserstack#60]
Running `npm i testcafe-browser-provider-browserstack` npm finds several high and moderate security vulnerabilities.

Running `npm audit` gives me these paths:
testcafe-browser-provider-browserstack > jimp > request > hawk > cryptiles (High)
testcafe-browser-provider-browserstack > jimp > request > stringstream (Moderate)
testcafe-browser-provider-browserstack > request > hawk > cryptiles (High)
testcafe-browser-provider-browserstack > request > stringstream (moderate)

Please consider updating request and jimp packages to resolve.

**Comment by AndreyBelym** [comment]
I've updated problematic dependencies in the `testcafe-browser-provider-browserstack@1.6.0` release.
