### ISSUE TITLE
malicous npm package

### ISSUE THREAD

**Issue by mcgoooo** [DevExpress/testcafe-browser-provider-browserstack#61]
Hello,

there seems to be, according to be a malicous payload getting inherited by your package
https://github.com/dominictarr/event-stream/issues/116#issuecomment-441135981
<img width="580" alt="screen shot 2018-11-26 at 17 19 19" src="https://user-images.githubusercontent.com/248888/49030566-92d00300-f19f-11e8-8055-9bb2b31823ac.png">

**Comment by dominiksipowicz** [comment]
ps-tree and browserstack-local already removed this event-stream

**Comment by kirovboris** [comment]
Thank you for the information, we'll fix it ASAP. 
/cc @AndreyBelym

**Comment by Exomnius** [comment]
Any update on this issue? Or can we assist with a PR?

**Comment by diversemix** [comment]
Willing to lend a hand too if it helps!

**Comment by kirovboris** [comment]
The fix was published in `testcafe-browser-provider-browserstack@1.5.1`
