### ISSUE TITLE
Safari Can't Connect to the Server 

### ISSUE THREAD

**Issue by jeremycy** [DevExpress/testcafe-browser-provider-browserstack#65]
I am seeing this error with Safari only, where browser just displays Can't connect to the server.   AFAIK this happens across different combination of OS/Safari version that I have tried.   Is there any special parameter/setup required to get Safari to work with testcafe/browserstack combo?

The following combinations all work fine for me except Safari (ex: "browserstack:safari@12.0:OS X Mojave")

chrome/OS X Sierra
firefox/OS X Sierra
IE11/ win 10
edge/win 10

Using latest version of plugin and testCafe 23

**Comment by jeremycy** [comment]
This appears to be Safari issue dealing with localhost...
Need to specify ip.  Closing this.....

**Comment by sketchynix** [comment]
"specify ip" was a bit unclear for me, so I am providing the solution I found when using a runner to connect to browserstack for anyone else who might come across the issue. 
I was passing in "localhost" to createTestCafe
```
createTestcafe("localhost")
```
instead if you pass in null it will use the device IP.
```
createTestCafe(null)
```
I also had to pass in a couple valid ports as described by https://www.browserstack.com/question/664
```
createTestCafe(null, "8000", "8001"
```

**Comment by stychu** [comment]
Thanks for posting solution @sketchynix it helped me!
