### ISSUE TITLE
Timeout when run in parallel

### ISSUE THREAD

**Issue by schoes** [DevExpress/testcafe-browser-provider-browserstack#67]
Hello I'm facing an issue where i can't run the tests on multiple browsers. they always get into timeout. why does this happen ?

**Comment by rangle-erickd** [comment]
I'm having same issue, using latest TestCafe version 1.0.1

**Comment by schoes** [comment]
i 've found a solution for this problem. you need to start each browserstack session independently.
Below you can see what i've done to fix this . Hope it helps
[solution.txt](https://github.com/DevExpress/testcafe-browser-provider-browserstack/files/2867916/solution.txt)

Regards
Sven

**Comment by insanesvk** [comment]
@schoes solution works, thanks

**Comment by owen-m1** [comment]
Similiar: https://github.com/DevExpress/testcafe/issues/2480
