### ISSUE TITLE
Tests running via Jenkins CI do not output the "Running tests in: " info

### ISSUE THREAD

**Issue by bennymeade** [DevExpress/testcafe-browser-provider-browserstack#77]
Hi, 

When I run my tests from my local machine directly on BrowserStack, the following info is returned for each test:
```
 Running tests in:
e2e-config search terms:  { items }
Loading tests...
 Running tests in:
 - Chrome 72.0.3626 / Windows 10.0.0 (https://automate.browserstack.com/builds/398e966f7a2b2eee79dd53b241938e25d23a7493/sessions/dc7f03784f874fada7c17defc007fe431b839)

Running on OSx
```

But when I trigger the same tests from Jenkins on BrowserStack, this info is not logged, it's just ignored:

```
e2e-config search terms:  { items }
Loading tests...
Running on Linux
```
How can I get this info via CI logging too?

**Comment by AndreyBelym** [comment]
This message is created by the [spec](https://www.npmjs.com/package/testcafe-reporter-spec) reporter. I guess you use a different reporter for your CI pipeline. If you configure this reporter to write to a file, you can use the `spec` reporter to show browser information in  the Jenkins console:
```
testcafe -r spec,xunit:report.xml ...
```

**Comment by bennymeade** [comment]
Fantastic, that was it exactly. And now my Jenkins logs include hyperlinks directly to the BS session. Thanks @AndreyBelym

**Comment by AndreyBelym** [comment]
Thank you for using TestCafe 😄
