### ISSUE TITLE
Long time taken to start a test on BrowserStack [Parallel Execution]

### ISSUE THREAD

**Issue by ckzgraphics** [DevExpress/testcafe-browser-provider-browserstack#82]
### Issue-

I am executing tests on BrowserStack in parallel and facing slowness while triggering the tests. I see a long delay before the test is started on BrowserStack. However, on the local browser, this is not visible. I have printed timestamp in my test script that shows the difference.

### Expected Behaviour-

There should no/less delay while starting the tests on BrowserStack

### Configuration-
- OS X High Sierra 10.13.6
- Chrome 75.0.3770
- TestCafe Version-

`cd /Users/my_user/Documents`
`testcafe --version`
`Using locally installed version of TestCafe.`
`1.3.3`

`cd /usr/local/bin`
`testcafe --version`
`0.21.1`

### TestCafe Test-
The test script can be found here- [simple_fixture.testcafe.js](https://gist.github.com/ckzgraphics/5857de09308617c0e380e99528ddaed1)

### Description-

If I am executing the tests on a single Chrome browser there is not much difference between local and BrowserStack execution. However, when I am executing the same tests on 5 Chrome browsers parallelly, there is a difference. And when the parallels are increased beyond 10 the difference increases significantly. :small_red_triangle:

**1.a- Local Execution on single chrome browser**

- Execution 1
Command executed from terminal => 15:48:14
The log line before fixture statement => 15:48:19
Difference=> 5 sec

- Execution 2
Command executed from terminal => 16:53:01
The log line before fixture statement => 16:53:03
Difference=> 2 sec

**1.b- BrowserStack Execution on single chrome browser**

- Execution 1
Command executed from terminal => 15:48:15
The log line before fixture statement => 15:48:23
Difference=> 8 sec 

- Execution 2
Command executed from terminal => 16:58:35
The log line before fixture statement => 16:58:41
Difference=> 6 sec

**2.a- Local Execution on 5 parallel chrome browsers**

- Execution 1
Command executed from terminal => 16:45:09
The log line before fixture statement => 16:45:12
Difference=> 3 sec :white_check_mark:

- Execution 2
Command executed from terminal => 17:03:53
The log line before fixture statement => 17:03:55
Difference=> 2 sec :white_check_mark:

**2.b- BrowserStack Execution on 5 parallel chrome browsers**

- Execution 1
Command executed from terminal => 16:45:08
The log line before fixture statement => 16:45:25
Difference=> 17 sec :heavy_exclamation_mark:

- Execution 2
Command executed from terminal => 17:03:52
The log line before fixture statement => 17:04:07
Difference=> 15 sec :bangbang:

**2.c- BrowserStack Execution on 20 parallel chrome browsers**

- Execution 1
Command executed from terminal => 17:15:16
The log line before fixture statement => 17:16:16
:o: :bangbang: Difference=> 1 mins :bangbang: :o:

### Log files-

- [Local single chrome execution](https://gist.github.com/ckzgraphics/b846b0cc591267626666b3c786b73c43)
- [BrowserStack single chrome execution](https://gist.github.com/ckzgraphics/7cdaa2a9fece2dac24de4273680b14f3)
- [Local 5 parallel chrome execution](https://gist.github.com/ckzgraphics/f585cbd440b2d9f448206c68d4d29f6c)
- [BrowserStack 5 parallel chrome execution](https://gist.github.com/ckzgraphics/a96e68c4b95f4340ac60a62b2d1cedd8)
- [BrowserStack 20 parallel chrome execution](https://gist.github.com/ckzgraphics/09ef250cf95a948f7ec14b75f9cb8ff9)  :o:

@AndreyBelym - Can you please provide some pointers here? What could be causing this behaviour?

**Let me know if any other details are required from my end to check this**

**Comment by aleks-pro** [comment]
Hello @ckzgraphics ,

Please specify first if you test an internal server or a public URL? It is important because for local testing, a secure connection is established between your machine and BrowserStack servers. This operation requires some extra time.

**Comment by ckzgraphics** [comment]
Hello @aleks-pro - I have executed the test on a public URL => https://the-internet.herokuapp.com/login

You can review the test as well - [simple_fixture.testcafe.js](https://gist.github.com/ckzgraphics/5857de09308617c0e380e99528ddaed1)

**Comment by AndreyBelym** [comment]
Could you please try to disable BrowserStack Local before starting tests by setting the `BROWSERSTACK_NO_LOCAL` environment variable to `1`? 
```
export BROWSERSTACK_NO_LOCAL=1;
testcafe ...
```

**Comment by ckzgraphics** [comment]
Hey @AndreyBelym - If I disable Local Testing it does not execute on BrowserStack since TestCafe opens the IP of my machine.

**Comment by AndreyBelym** [comment]
Yes, of course, it's my mistake. I have suspicions that BrowserStack Local causes this performance impact, but I still have to do some more tests.

**Comment by ckzgraphics** [comment]
Hi @AndreyBelym - Can you [review these changes](https://github.com/yashLadha/testcafe-browser-provider-browserstack/commit/0056eca67c5f266184032ad81ba5dd98038ca2f3) and add your comments?

**Comment by AlexKamaev** [comment]
@ckzgraphics 
That PR was significantly changed since @AndreyBelym watched it last time, so it's required to review it from the beginning. We will check it, however, we cannot give you any estimates.
