### ISSUE TITLE
Testcafe browser restarts spawning extra browserstack runs that don't do anything

### ISSUE THREAD

**Issue by DavidSampson** [DevExpress/testcafe-browser-provider-browserstack#87]
Testcafe restarts the browser if it experiences issues during the test run (see: [testcafe #1815](https://github.com/DevExpress/testcafe/issues/1815)). Separately, we are seeing an issue where, during longer test runs, an error is generated that hangs the browser, prompting a restart (see: [testcafe-hammerhead #2013](https://github.com/DevExpress/testcafe-hammerhead/issues/2013)).

The issue is, when this happens to us while testing on browserstack Automate (not JS testing), the following happens:

1. The original test run closes
2. A new browserstack instance is spawned. Nothing happens in this instance, it sits idle for 90 seconds before browserstack closes it due to it's idle time out.
3. A third browserstack instance is spawned, and the tests keep going.

Best case scenario of what should happen: the same browserstack instance is used for the entirety of the test run. However if this is impossible, the idle browserstack instance should not be spawned, it clogs up the browserstack instance limit and makes debugging difficult.

Here's an example of what one of the idle browserstack instances looks like:
![browserstacknullrun](https://user-images.githubusercontent.com/11844890/67312809-9101e300-f4c7-11e9-94b9-59833164b29b.PNG)

**Comment by miherlosev** [comment]
Hi @DavidSampson 

Please wait until the https://github.com/DevExpress/testcafe-hammerhead/issues/2013 is fixed. After that, run your tests with the newest TestCafe version and reopen this issue if the problem persists.
