### ISSUE TITLE
StatusCodeError: 403 invalid id - trying to delete worker twice

### ISSUE THREAD

**Issue by mansn** [DevExpress/testcafe-browser-provider-browserstack#88]
Hi,

I think there's a potential problem with the current logic which is here: 
https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/master/src/backends/js-testing.js#L100

Sometimes (~8% of all our TestCafé runs) I'm getting the following error
`StatusCodeError: 403 - {"message":"Validation Failed","errors":[{"field":"id","code":"invalid"}]}`

I manually added some console.log() statements in `node_modules/testcafe-browser-provider-browserstack/lib/backends/js-testing.js` to investigate what was going on.

I found out that a DELETE request to delete a worker is executed **twice** sometimes. When this happens, the second DELETE request occurs **after** the TestCafé server has been stopped (after executing `.close()` on the TestCafé server instance). I'm suspecting that the latter request is the delayed one. The second request fails due to the worker not existing anymore.

My test suite has an execution time of approximately 20-30 seconds, in case that's valuable information.

What's the purpose of the logic to sometimes delay the request to browserstack? I couldn't find the same logic for the "BrowserStack Automate" integration, so it seems that it's specific for "BrowserStack JS Testing"?

I'll try to create a generic scenario where this is reproducible.

**Comment by Farfurix** [comment]
@mansn 

Hello,

This [PR](https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/84) will remove [th](https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/84/files#diff-4c11ab94fe2b06210bcd7a06e5f6d5e7L100-L105)[is](https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/84/files#diff-4c11ab94fe2b06210bcd7a06e5f6d5e7L100-L105)[ code](https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/84/files#diff-4c11ab94fe2b06210bcd7a06e5f6d5e7L100-L105), please stay tuned for updates in this thread: [https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/84](https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/84).
After merging and releasing a new version, you will be able to check your test scenario. Please feel free to create a new bug report if you have any problem with this.

**Comment by yashLadha** [comment]
Hey @mansn You can try out https://github.com/browserstack/testcafe-browser-provider-browserstack in meantime.
