### ISSUE TITLE
Environment variable to add a Build Title in BrowserStack dashboard

### ISSUE THREAD

**Issue by bennymeade** [DevExpress/testcafe-browser-provider-browserstack#94]
BrowserStack new dashboard "/dashboard/v2/" displays a grouped Build Title, but mine shows as Untitled Build.

What environment variable do I pass to add a Build Title?

![image](https://user-images.githubusercontent.com/1033474/68662461-c2088d00-0534-11ea-9d14-7be9fec3f802.png)

I already pass:
export BROWSERSTACK_USERNAME=xxx
export $BROWSERSTACK_ACCESS_KEY
export BROWSERSTACK_VIDEO=true
export BROWSERSTACK_CONSOLE=info
export BROWSERSTACK_PROJECT_NAME="xxx"
export BROWSERSTACK_DEBUG=true
export BROWSERSTACK_USE_AUTOMATE="1"

**Comment by arubtsov** [comment]
Hello @bennymeade,

As it is stated in the [description](https://github.com/DevExpress/testcafe-browser-provider-browserstack#usage), you need to add the `BROWSERSTACK_BUILD_ID` environment variable.
