### ISSUE TITLE
Unable to use browserstack for SSL testcafe connections

### ISSUE THREAD

**Issue by monicainde** [DevExpress/testcafe-browser-provider-browserstack#96]
Browserstack allows testcafe ssl connections with chrome at the moment. 
To enable ssl connections on non-chrome browser browserstack requires to set a `acceptSslCerts` flag.

I have already raised a pull request to enable this flag in the plug-in :)

**Comment by Farfurix** [comment]
@monicainde 

Hello,

Thank you for your PR. Our team needs time to check it out. Please stay tuned to our updates here: https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/95.
