### ISSUE TITLE
npm ERR! notarget No matching version found for testcafe-browser-provider-browserstack@1.11.0

### ISSUE THREAD

**Issue by bennymeade** [DevExpress/testcafe-browser-provider-browserstack#98]
**Running: $ npm install testcafe-browser-provider-browserstack@latest**
Pulls down version 1.10.1 as latest.

"testcafe-browser-provider-browserstack": "^1.10.1"

**Running: $ npm install testcafe-browser-provider-browserstack@1.11.0**
npm ERR! notarget No matching version found for testcafe-browser-provider-browserstack@1.11.0.

I see both v1.10.1 and v1.11.0 says it was released 5 days ago, which may be part of the issue.

**Comment by AlexSkorkin** [comment]
Thank you for bringing this to our attention. We will re-publish the new 1.11.0 version on npm soon.

In the meantime, you can download the latest 1.11.0 version from the [Releses](https://github.com/DevExpress/testcafe-browser-provider-browserstack/releases) section and build it locally by running `npm install`.

**Comment by AndreyBelym** [comment]
I apologize for any inconvenience, `testcafe-browser-provider-browserstack@1.11.0` was re-published and should be available now.

**Comment by bennymeade** [comment]
Confirmed fixed: "testcafe-browser-provider-browserstack": "^1.11.0"

**Comment by AlexSkorkin** [comment]
Thank you for your confirmation.
