### ISSUE TITLE
Can't run tests using beta browser aliases

### ISSUE THREAD

**Issue by dennmart** [DevExpress/testcafe-browser-provider-browserstack#99]
I recently began running my project's TestCafe tests on Browserstack using this library. I noticed that I can't run the tests on beta browsers, although

For example, when I run `testcafe -b browserstack` to verify available browser aliases I can use, I can see beta versions of many browsers and operating systems (like `"browserstack:chrome@80.0 beta:OS X Catalina"` or `"browserstack:firefox@72.0 beta:Windows 7"`). However, if I try running my tests specifying one of these aliases (e.g. `testcafe "browserstack:chrome@80.0 beta:OS X Catalina" "my_test.js"`), I get the following error indicating that the browser alias is invalid:

```
ERROR Unable to find the browser. "browserstack:chrome@80.0 beta:OS X Catalina" is not a browser alias or path to an executable file.
```

Using non-beta browsers works as expected with no issues.

I'm not sure if this is the issue, but looking at the source code I noticed [this line](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/master/src/index.js#L140) is converting the browser version to a number when doing its comparison. Since the browser version is using 'beta' as part of its string (e.g. "80.0 beta"), it looks like that's what's causing the mismatch.

**Comment by AlexKamaev** [comment]
This behavior is incorrect. Thank you for pointing out this issue to us.
As a workaround, do not specify the browser version as in the following line: `"browserstack:chrome:OS X Catalina"`. In this case, the beta version will be used.
